# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shoppingwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShoppingWindow(object):
    def setupUi(self, ShoppingWindow):
        ShoppingWindow.setObjectName("ShoppingWindow")
        ShoppingWindow.resize(1158, 648)
        self.centralwidget = QtWidgets.QWidget(ShoppingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(680, 10, 351, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settlementButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.settlementButton.setFont(font)
        self.settlementButton.setObjectName("settlementButton")
        self.gridLayout_2.addWidget(self.settlementButton, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.historyTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.historyTableWidget.setObjectName("historyTableWidget")
        self.historyTableWidget.setColumnCount(0)
        self.historyTableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.historyTableWidget, 1, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 371, 571))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.salesTableWidget = QtWidgets.QTableWidget(self.layoutWidget2)
        self.salesTableWidget.setObjectName("salesTableWidget")
        self.salesTableWidget.setColumnCount(0)
        self.salesTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.salesTableWidget, 1, 0, 1, 1)
        self.returnButton = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.gridLayout.addWidget(self.returnButton, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(401, 160, 272, 153))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.amountLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.amountLineEdit.setObjectName("amountLineEdit")
        self.gridLayout_3.addWidget(self.amountLineEdit, 1, 0, 1, 1)
        self.selectButton = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.selectButton.setFont(font)
        self.selectButton.setObjectName("selectButton")
        self.gridLayout_3.addWidget(self.selectButton, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.updateButton = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(16)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout_3.addWidget(self.updateButton, 3, 0, 1, 1)
        ShoppingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ShoppingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 25))
        self.menubar.setObjectName("menubar")
        ShoppingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ShoppingWindow)
        self.statusbar.setObjectName("statusbar")
        ShoppingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ShoppingWindow)
        QtCore.QMetaObject.connectSlotsByName(ShoppingWindow)

    def retranslateUi(self, ShoppingWindow):
        _translate = QtCore.QCoreApplication.translate
        ShoppingWindow.setWindowTitle(_translate("ShoppingWindow", "MainWindow"))
        self.settlementButton.setText(_translate("ShoppingWindow", "结算"))
        self.label_2.setText(_translate("ShoppingWindow", "购物车"))
        self.returnButton.setText(_translate("ShoppingWindow", "返回"))
        self.label.setText(_translate("ShoppingWindow", "正在销售"))
        self.selectButton.setText(_translate("ShoppingWindow", "选择"))
        self.label_3.setText(_translate("ShoppingWindow", "请输入要购买的数量："))
        self.updateButton.setText(_translate("ShoppingWindow", "删除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShoppingWindow = QtWidgets.QMainWindow()
    ui = Ui_ShoppingWindow()
    ui.setupUi(ShoppingWindow)
    ShoppingWindow.show()
    sys.exit(app.exec_())

